.

diff --git a/.azure-pipelines-templates/deploy_aci.yml b/.azure-pipelines-templates/deploy_aci.yml
--- a/.azure-pipelines-templates/deploy_aci.yml
+++ b/.azure-pipelines-templates/deploy_aci.yml
@@ -147,10 +147,12 @@ jobs:
 
       - script: |
           echo $(SecondaryIpAddresses) > ~/secondary_ip_addresses
+          cat ~/secondary_ip_addresses
           mapfile -t IP_ADDR_LIST <<< $(echo "$(IpAddresses)" | awk '{print $2}')
           for IP_ADDR in "${IP_ADDR_LIST[@]}"; do
             ssh agent@$IP_ADDR -o "StrictHostKeyChecking no" 'echo "Connected successfully"'
             scp ~/secondary_ip_addresses agent@$IP_ADDR:/home/agent/secondary_ip_addresses
+            ssh agent@$IP_ADDR -o "StrictHostKeyChecking no" 'cat /home/agent/secondary_ip_addresses'
           done
 
   - job: cleanup_aci
@@ -187,11 +189,11 @@ jobs:
         name: cleanup_workspace
         displayName: "Cleanup Workspace"
 
-      - script: |
-          set -ex
-          python3.8 -m venv ./scripts/azure_deployment/.env
-          source ./scripts/azure_deployment/.env/bin/activate
-          pip install -r ./scripts/azure_deployment/requirements.txt
-          python3.8 scripts/azure_deployment/arm_template.py remove aci --subscription-id $(CCF_AZURE_SUBSCRIPTION_ID) --resource-group ccf-aci --aci-type dynamic-agent --deployment-name ci-$(Build.BuildNumber)
-        name: cleanup_aci
-        displayName: "Delete the ACI and Azure Deployment"
+      # - script: |
+      #     set -ex
+      #     python3.8 -m venv ./scripts/azure_deployment/.env
+      #     source ./scripts/azure_deployment/.env/bin/activate
+      #     pip install -r ./scripts/azure_deployment/requirements.txt
+      #     python3.8 scripts/azure_deployment/arm_template.py remove aci --subscription-id $(CCF_AZURE_SUBSCRIPTION_ID) --resource-group ccf-aci --aci-type dynamic-agent --deployment-name ci-$(Build.BuildNumber)
+      #   name: cleanup_aci
+      #   displayName: "Delete the ACI and Azure Deployment"
