[Experiment] Git checkout mtime canary

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,6 +39,14 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: "Check files mtime"
+        run: |
+          set -ex
+          git ls-files -z | xargs -0 stat -c "%Y" | sort -u
+          # Fail if there is more than one timestamp
+          git ls-files -z | xargs -0 stat -c "%Y" | sort -u | awk 'NR>1 {exit 1}'
+        shell: bash
+
       - name: "Install dependencies"
         shell: bash
         run: |
